### ISSUE TITLE
Translation: ar

### ISSUE THREAD

**Issue by mosid** [pytesNET/tail.DateTime#1]
### Months
-   January: "يناير"
-   February: "فبراير"
-   March: "مارس"
-   April: "أبريل"
-   May: "مايو"
-   June: "يونيو"
-   July: "يوليو"
-   August: "أغسطس"
-   September: "سبتمبر"
-   October: "أكتوبر"
-   November: "نوفمبر"
-   December: "ديسمبر"

### Weeks
-   Sunday (SUN): "الأحد (أحد)"
-   Monday (MON): "الإثنين (إثن)"
-   Tuesday (TUE): "الثلاثاء (ثلا)"
-   Wednesday (WED): "الأربعاء (أرب)"
-   Thursday (THU): "الخميس (خمي)"
-   Friday (FRI): "الجمعة (جمع)"
-   Saturday (SAT): "السبت (سبت)"

### Time
-   Hours: "ساعة"
-   Minutes: "دقيقة"
-   Seconds: "ثانية"

### Strings
-   Select a Month: "إختر الشهر"
-   Select a Year: "إخنر السنة"
-   Select a Decade: "إختر العقد"
-   Select a Time: "إختر الوقت"

**Comment by SamBrishes** [comment]
Hello,

really thanks for your translation. It was really hard to copy your strings into my document, because my Mouse Cursor was jumping right to left to right, and my Editors (Notepad++ and Atom) does always reversed like anything after pasting your strings into it.

I will try to make the HTML Output fully RTL compatible to support your arabic translation.

Thanks.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

Version 0.4.1 is out now and includes your translation (and RTL support). Thanks for your help!

Sincerely,
Sam.
