### ISSUE TITLE
Uncaught TypeError: tail.DateTime(...).selectDate is not a function

### ISSUE THREAD

**Issue by mahadoang** [pytesNET/tail.DateTime#11]
```
tail.DateTime("#time-show", {
	dateFormat: "YYYY-mm-dd",
	position:'left',
	timeFormat: false,
}).selectDate(function(a,b,c,e,f,g){
	console.log(a);
});
```

Error : Uncaught TypeError: tail.DateTime(...).selectDate is not a function

**Comment by SamBrishes** [comment]
Hellow,

The `.selectDate()` method doesn't allow a callback function as parameter (as used on your snippet). You need to pass the desired date/time data, [as shown on this jsFiddle](https://jsfiddle.net/SamBrishes/rvkja3z9/). The used snippet will select the 12th November 2018 (because the [month number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) is counting at 0, for January).

Please try the following examples:
```javascript
tail.DateTime("#time-show", {
    position: "left",
    dateFormat: "YYYY-mm-dd",
    timeFormat: false,
}).selectDate(2018, 10, 12);


// You can also try to assign the instance to a variable before
var instance = tail.DateTime("#time-show", {
    position: "left",
    dateFormat: "YYYY-mm-dd",
    timeFormat: false,
});
instance.selectDate(2018, 10, 12);
```

If you still have this issue, please mention the used browser, and the used tail.DateTime version too. Thanks.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
I'm closing this issue, please re-open if, if the issue still exists with the latest version.

Happy New Year. :tada: 

Thanks.
