### ISSUE TITLE
Export to module for commonJS instead of attaching to Window

### ISSUE THREAD

**Issue by cgfarmer4** [pytesNET/tail.DateTime#26]
Would be nice to be able to rename tail.dateTime to my own variable not attached to the global when using CommonJS structure.

const dt = require('tail.dateTime');

currently this dt does not get assigned.

**Comment by SamBrishes** [comment]
Hellow,

thanks for your request. 

With CommonJS you mean a [module ecosystem](https://en.wikipedia.org/wiki/CommonJS) outside of the browsers ecosystem, right? Because the tail.DateTime script doesn't support any use outside of the web browser, **but** it already supports [the AMD known module format](https://github.com/pytesNET/tail.DateTime/blob/master/js/tail.datetime.js#L13) within the browser using **requireJS** (as used on [a special demonstration page](https://github.com/pytesNET/tail.DateTime/blob/gh-pages/assets/js/main.js#L4)).

Sincerely,
Sam.

**Comment by cgfarmer4** [comment]
Not really, if you’re using NPM, you should supply exports that can be hooked into. 

CommonJS can work in the browser with Browserify and Webpack. 

-Chase

**Comment by SamBrishes** [comment]
Hellow,

thanks. I looked at browserify, and I'll try to implement a respective `module.exports` line in my factory IIFE function.

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

I added support for browserify / browser-based modules.

Sincerely,
Sam.

**Comment by cgfarmer4** [comment]
Many thanks!

-Chase
