### ISSUE TITLE
Tail has another feature you don't mention - No Unix Command

### ISSUE THREAD

**Issue by jimruss1** [pytesNET/tail.DateTime#28]
Some other date/time calendar programs have a complicated structure requiring the programmer to go to the CLI (terminal for mac users) and to a) learn the directory structure (I believe different from win to mac) and b) relearn their Unix commands.  'No Unix commands required'.

If directory structure is different for mac users, then many of the Open Source utility programs probably won't create the correct directory structure and won't download programs into the correct directories (folder for mac uses).

You use the term AMD frequently.  What does that mean?

**Comment by SamBrishes** [comment]
Hellow,

I'm sorry? I'm not really sure what you mean with another feature? The tail.DateTime script doesn't require any UNIX commands, because it isn't capable outside the browsers JavaScript environment. Please don't confuse it with the [tail](https://en.wikipedia.org/wiki/Tail_(Unix)) program (or any other `tail` named software)! The name "tail" is just a prefix I'm using for any JavaScript based project.

I never used macOS (or any other Apple device / OS), I'm working on Windows 10 and GNU/Linux machines. I've no idea about the directory structure on a macOS system. :D

I'm using the AMD term a single time in the README.md file. It just means "**A**synchronous **M**odule **D**efinition". It brings the - from commonJS known - module definition to the browser. More information can be found on [Wikipedia](https://de.wikipedia.org/wiki/Asynchronous_module_definition) or [requireJS](https://requirejs.org/docs/whyamd.html) (which implements an AMD structure to the browser).

Sincerely,
Sam.

**Comment by SamBrishes** [comment]
Hellow,

I guess this issue is clear? 

I close it for now, if you still have any question, feel free to reopen it.

Thanks.

Sincerely, 
Sam.
